# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 0mu & dd-han 的發廚筆記
email: m85091081@gmail.com
description: 反正就只是個廚站 # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reimu.dd-han.tw" # the base hostname & protocol for your site
github_username:  orgs/0mu-Project
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
# Build settings
markdown: kramdown
